"""SQL Validator and Sanitizer for preventing SQL injection attacks.

This module provides validation and sanitization of SQL queries generated by LLM
to prevent malicious operations like DROP, DELETE, INSERT, etc.
"""

from __future__ import annotations

import re
from typing import List, Set, Tuple


class SQLValidator:
    """Validates and sanitizes SQL queries generated by LLM.
    
    Uses a whitelist approach: only SELECT statements are allowed.
    All DDL (Data Definition Language) and DML (Data Manipulation Language)
    operations except SELECT are blocked.
    """
    
    # Allowed SQL operations (whitelist)
    ALLOWED_STATEMENTS: Set[str] = {"SELECT"}
    
    # Forbidden keywords that should NEVER appear in generated SQL
    FORBIDDEN_KEYWORDS: Set[str] = {
        # DDL - Data Definition Language
        "DROP", "ALTER", "CREATE", "TRUNCATE", "RENAME",
        # DML - Data Manipulation Language (except SELECT)
        "DELETE", "INSERT", "UPDATE", "REPLACE", "MERGE",
        # DCL - Data Control Language
        "GRANT", "REVOKE",
        # TCL - Transaction Control Language
        "COMMIT", "ROLLBACK", "SAVEPOINT",
        # SQLite specific dangerous commands
        "ATTACH", "DETACH", "VACUUM", "REINDEX", "PRAGMA",
        # Execution commands
        "EXEC", "EXECUTE", "CALL",
    }
    
    # Forbidden patterns (regex) that indicate SQL injection attempts
    FORBIDDEN_PATTERNS: List[str] = [
        r";\s*(?:DROP|DELETE|INSERT|UPDATE|ALTER|CREATE)",  # Multiple statements with dangerous ops
        r"--",  # SQL line comments (can hide malicious code)
        r"/\*",  # Block comments start
        r"\*/",  # Block comments end
        r"UNION\s+ALL\s+SELECT",  # Union-based injection
        r"UNION\s+SELECT",  # Union-based injection
        r"INTO\s+OUTFILE",  # File write attack
        r"INTO\s+DUMPFILE",  # File write attack
        r"LOAD_FILE\s*\(",  # File read attack
        r"LOAD\s+DATA",  # Data loading attack
        r"\\x[0-9a-fA-F]+",  # Hex encoding (obfuscation)
        r"CHAR\s*\(\s*\d+",  # CHAR encoding (obfuscation)
        r"0x[0-9a-fA-F]+",  # Hex literals (potential obfuscation)
    ]
    
    # Default LIMIT to add if missing
    DEFAULT_LIMIT: int = 100
    
    def __init__(self, allowed_tables: List[str] | None = None):
        """Initialize the validator.
        
        Args:
            allowed_tables: Optional list of table names that are allowed to be queried.
                           If None, all tables are allowed.
        """
        self._allowed_tables = set(t.lower() for t in allowed_tables) if allowed_tables else None
    
    def validate(self, sql: str) -> Tuple[bool, str, str]:
        """Validate SQL query for safety.
        
        Args:
            sql: The SQL query to validate.
            
        Returns:
            Tuple of (is_valid, sanitized_sql, error_message).
            - is_valid: True if the query is safe to execute.
            - sanitized_sql: The sanitized SQL (with LIMIT added if missing).
            - error_message: Error description if validation failed.
        """
        if not sql or not sql.strip():
            return False, "", "Empty SQL query"
        
        sql = sql.strip()
        sql_upper = sql.upper()
        
        # 1. Check for forbidden keywords (word boundary to avoid false positives)
        for keyword in self.FORBIDDEN_KEYWORDS:
            # Use word boundary \b to match whole words only
            # This prevents matching "UPDATED_AT" when looking for "UPDATE"
            if re.search(rf'\b{keyword}\b', sql_upper):
                return False, "", f"Forbidden SQL keyword detected: {keyword}"
        
        # 2. Check for forbidden patterns
        for pattern in self.FORBIDDEN_PATTERNS:
            if re.search(pattern, sql, re.IGNORECASE):
                return False, "", f"Forbidden SQL pattern detected: potential injection attempt"
        
        # 3. Check for multiple statements (semicolon not at the end)
        semicolon_count = sql.count(';')
        if semicolon_count > 1:
            return False, "", "Multiple SQL statements not allowed"
        if semicolon_count == 1 and not sql.rstrip().endswith(';'):
            return False, "", "Multiple SQL statements detected (semicolon in middle)"
        
        # 4. Verify it starts with SELECT
        sql_normalized = ' '.join(sql_upper.split())  # Normalize whitespace
        if not sql_normalized.startswith("SELECT"):
            return False, "", "Only SELECT statements are allowed"
        
        # 5. Check table names if whitelist is configured
        if self._allowed_tables:
            tables_in_query = self._extract_table_names(sql)
            unauthorized = tables_in_query - self._allowed_tables
            if unauthorized:
                return False, "", f"Unauthorized table access: {', '.join(unauthorized)}"
        
        # 6. Ensure LIMIT clause exists (prevent full table dumps)
        sanitized_sql = self._ensure_limit(sql)
        
        return True, sanitized_sql, ""
    
    def _extract_table_names(self, sql: str) -> Set[str]:
        """Extract table names from SQL query.
        
        Args:
            sql: The SQL query to analyze.
            
        Returns:
            Set of lowercase table names found in the query.
        """
        tables: Set[str] = set()
        
        # Match table names after FROM or JOIN keywords
        # Pattern: FROM table_name or JOIN table_name
        # Handles optional schema prefix: schema.table_name
        pattern = r'(?:FROM|JOIN)\s+(?:[\w]+\.)?([a-zA-Z_][a-zA-Z0-9_]*)'
        matches = re.findall(pattern, sql, re.IGNORECASE)
        tables.update(m.lower() for m in matches)
        
        return tables
    
    def _ensure_limit(self, sql: str) -> str:
        """Ensure SQL has a LIMIT clause, adding one if missing.
        
        Args:
            sql: The SQL query.
            
        Returns:
            SQL with LIMIT clause guaranteed.
        """
        sql_upper = sql.upper()
        
        # Check if LIMIT already exists
        if "LIMIT" in sql_upper:
            return sql
        
        # Remove trailing semicolon if present
        sql_clean = sql.rstrip(';').strip()
        
        # Add default LIMIT
        return f"{sql_clean} LIMIT {self.DEFAULT_LIMIT}"


class SQLSanitizer:
    """Additional SQL sanitization utilities."""
    
    @staticmethod
    def escape_string_literal(value: str) -> str:
        """Escape string for safe use in SQL string literals.
        
        Args:
            value: The string value to escape.
            
        Returns:
            Escaped string safe for SQL use.
        """
        # SQLite uses '' for escaping single quotes
        return value.replace("'", "''")
    
    @staticmethod
    def remove_dangerous_chars(sql: str) -> str:
        """Remove potentially dangerous control characters from SQL.
        
        Args:
            sql: The SQL query to clean.
            
        Returns:
            Cleaned SQL string.
        """
        # Remove null bytes and other control characters (except newlines/tabs)
        return re.sub(r'[\x00-\x08\x0b\x0c\x0e-\x1f\x7f]', '', sql)
    
    @staticmethod
    def normalize_whitespace(sql: str) -> str:
        """Normalize whitespace in SQL for consistent parsing.
        
        Args:
            sql: The SQL query to normalize.
            
        Returns:
            SQL with normalized whitespace.
        """
        # Replace multiple whitespace with single space, preserve structure
        lines = sql.split('\n')
        normalized_lines = [' '.join(line.split()) for line in lines]
        return '\n'.join(line for line in normalized_lines if line)

